language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t deepaksaroha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deepaksaroha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-490747880402"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $access_key_id
    secret_access_key: "$secret_access_key"